services:
  app:
    container_name: igmo-backend-local
    env_file:
      - path: .env
        required: false
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: ${SERVER_PORT:-8080}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
      IGMO_DEPLOYMENT_SLOT: ${IGMO_DEPLOYMENT_SLOT:-blue}
      IGMO_DEPLOYMENT_PORT: ${IGMO_DEPLOYMENT_PORT:-8080}
      LOGGING_STRUCTURED_FORMAT_CONSOLE: logstash
      IGMO_REDIS_HOST: ${IGMO_REDIS_HOST:-redis}
      IGMO_REDIS_PORT: ${IGMO_REDIS_PORT:-6379}
    ports:
      - "8080:8080"
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: "3"
    restart: always
    networks:
      - igmo-runtime

networks:
  igmo-runtime:
    external: true
    name: igmo-runtime
