server {
    listen 80;
    listen [::]:80;

    server_name monitoring.igmo.co.kr;

    access_log /var/log/nginx/monitoring.access.log;
    error_log /var/log/nginx/monitoring.error.log warn;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 302 https://largeivy1754.grafana.net$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name monitoring.igmo.co.kr;

    ssl_certificate /etc/letsencrypt/live/monitoring.igmo.co.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/monitoring.igmo.co.kr/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    access_log /var/log/nginx/monitoring.access.log;
    error_log /var/log/nginx/monitoring.error.log warn;

    location / {
        return 302 https://largeivy1754.grafana.net$request_uri;
    }
}
