package com.igmo.web.dto;

public enum RoomMessageType {
    LOBBY_SNAPSHOT,
    PROMPT_SUBMISSION_SNAPSHOT,
    ROUND_SNAPSHOT,
    VOTE_SNAPSHOT,
    ROUND_RESULT_SNAPSHOT,
    GAME_RESULT_SNAPSHOT
}
