global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: igmo-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
        labels:
          service: igmo
          environment: local

  - job_name: igmo-app-slot-health
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
        labels:
          service: igmo
          environment: local
          slot: blue
          port: "8080"
      - targets:
          - host.docker.internal:8081
        labels:
          service: igmo
          environment: local
          slot: green
          port: "8081"

  - job_name: redis
    static_configs:
      - targets:
          - redis-exporter:9121
        labels:
          service: redis
          environment: local
