global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: igmo-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 127.0.0.1:8080
        labels:
          service: igmo
          environment: production

  - job_name: ec2-host
    static_configs:
      - targets:
          - 127.0.0.1:9100
        labels:
          instance: igmo-production
          environment: production
